services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      network: host
    container_name: hirefy-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - DATABASE_URL=sqlite:///db.sqlite3
    networks:
      - hirefy-network
    restart: unless-stopped

  scrapper:
    build:
      context: ./scraping
      dockerfile: Dockerfile
    container_name: hirefy-scrapper
    ports:
      - "5000:5000"
    volumes:
      - ./scraping:/app
    networks:
      - hirefy-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      network: host
    container_name: hirefy-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - backend
    networks:
      - hirefy-network
    restart: unless-stopped

networks:
  hirefy-network:
    driver: bridge
