# Generated by Django 6.0.5 on 2026-05-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
