# Generated by Django 6.0.5 on 2026-05-18 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='skills',
        ),
    ]
