# Generated by Django 6.0.5 on 2026-05-06 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('site_url', models.URLField(blank=True, max_length=500, null=True)),
                ('recruiter', models.OneToOneField(limit_choices_to={'user_type': 'RECRUTADOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements_mandatory', models.TextField()),
                ('requirements_desirable', models.TextField(blank=True, null=True)),
                ('level', models.CharField(choices=[('ESTAGIO', 'Estágio'), ('JUNIOR', 'Júnior'), ('PLENO', 'Pleno'), ('SENIOR', 'Sênior')], max_length=20)),
                ('education_level', models.CharField(max_length=255)),
                ('location_type', models.CharField(choices=[('REMOTO', 'Remoto'), ('PRESENCIAL', 'Presencial'), ('HIBRIDO', 'Híbrido')], max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='Brasil', max_length=100)),
                ('contract_type', models.CharField(choices=[('CLT', 'CLT'), ('PJ', 'PJ'), ('ESTAGIO', 'Estágio')], max_length=20)),
                ('workload', models.CharField(max_length=100)),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('benefits', models.TextField(blank=True, null=True)),
                ('deadline_date', models.DateField(blank=True, null=True)),
                ('gupy_link', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('ATIVA', 'Ativa'), ('PAUSADA', 'Pausada'), ('ENCERRADA', 'Encerrada')], default='ATIVA', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.company')),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
                'ordering': ['-created_at'],
            },
        ),
    ]
