# Generated by Django 6.0.5 on 2026-06-01 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_company_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
